language: java
jdk:
  - oraclejdk8
before_install:

script:
  -  mvn clean
  -  mvn compile
  -  mvn test jacoco:report org.pitest:pitest-maven:mutationCoverage

after_success:
  - mvn coveralls:report